[plugin]
repository = "https://github.com/ars-magna/OopsAllLalafells.git"
commit = "669445ae79443477a3157a9075c6f64cd68fd0ad"
owners = ["ars-magna"]
project_path = "Oops, All Lalafells"
changelog = "D17 Compliance"